// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // checks if the code is running in the web
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqS4HYGBauMCkvCnZvkVxUAjHvau-McUg',
    appId: '1:492643157550:web:f47079c4b15ebf64da01bf',
    messagingSenderId: '492643157550',
    projectId: 'my-diary-cac79',
    authDomain: 'my-diary-cac79.firebaseapp.com',
    storageBucket: 'my-diary-cac79.appspot.com',
    measurementId: 'G-BZL8ZJQST0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnz00iTgAO-Ms3j6H8ZPv8QvfC097a_ps',
    appId: '1:492643157550:android:0923161e66283ca6da01bf',
    messagingSenderId: '492643157550',
    projectId: 'my-diary-cac79',
    storageBucket: 'my-diary-cac79.appspot.com',
  );
}
